apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scalable-ai-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: scalable-ai
  source:
    repoURL: https://github.com/your-org/scalable-ai-infra-config.git
    targetRevision: HEAD
    path: k8s/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: scalable-ai-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
